// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "Algorithms": Application Contexts
//
// Command:
// $ goagen
// --design=github.com/schiob/dijkstra/design
// --out=$(GOPATH)/src/github.com/schiob/dijkstra
// --version=v1.2.0-dirty

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

// ComputeDijkstraContext provides the dijkstra compute action context.
type ComputeDijkstraContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	Payload *GraphPayload
}

// NewComputeDijkstraContext parses the incoming request URL and body, performs validations and creates the
// context used by the dijkstra controller compute action.
func NewComputeDijkstraContext(ctx context.Context, r *http.Request, service *goa.Service) (*ComputeDijkstraContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := ComputeDijkstraContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *ComputeDijkstraContext) OK(r *Graphresult) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/vnd.graphresult+json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// BadRequest sends a HTTP response with status code 400.
func (ctx *ComputeDijkstraContext) BadRequest(r error) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/vnd.goa.error")
	return ctx.ResponseData.Service.Send(ctx.Context, 400, r)
}
