// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "Algorithms": swagger TestHelpers
//
// Command:
// $ goagen
// --design=github.com/schiob/dijkstra/design
// --out=$(GOPATH)/src/github.com/schiob/dijkstra
// --version=v1.2.0-dirty

package test
